# Generated by Django 4.2.2 on 2023-06-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                ("content", models.TextField(verbose_name="Contenido")),
                ("image", models.ImageField(upload_to="", verbose_name="Imagen")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "articulo",
                "verbose_name_plural": "articulos",
                "ordering": ["-created"],
            },
        ),
    ]
