# Generated by Django 4.2.2 on 2023-06-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_article_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
